### ISSUE TITLE
请问密码如何获取？

### ISSUE THREAD

**Issue by zdbss** [P-boss/AI-qiangguo#1]
请问密码如何获取？

**Comment by P-boss** [comment]
目前为内部朋友几个自用，题库是通用的，可以用在其他开源项目上。

**Comment by P-boss** [comment]
目前为内部朋友几个自用，题库是通用的，可以用在其他开源项目上。

**Comment by yuechen90** [comment]
用识别码获取激活码，找不到，是不是你们内部用，我们外部不能用
